import { StyleSheet } from "react-native";
import { colors } from "../../styles/globalStyles";

const baseCard = {
  backgroundColor: colors.white,
  borderRadius: 16,
  padding: 16,
  shadowColor: "#000000",
  shadowOpacity: 0.06,
  shadowRadius: 8,
  shadowOffset: { width: 0, height: 4 },
  elevation: 2,
};

export const styles = StyleSheet.create({
  activityDetail__container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  activityDetail__scrollContent: {
    flexGrow: 1,
    paddingTop: 0,
    paddingBottom: 32,
    gap: 16,
  },
  activityDetail__header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 18,
    backgroundColor: colors.white,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.lightGray,
  },
  activityDetail__headerTitle: {
    fontSize: 18,
    fontFamily: "Inter-Bold",
    color: colors.black,
  },
  activityDetail__headerSubtitle: {
    fontSize: 14,
    fontFamily: "Inter-Normal",
    color: colors.gray,
  },
  activityDetail__summaryCard: {
    ...baseCard,
    marginHorizontal: 16,
    alignItems: "center",
    gap: 12,
  },
  activityDetail__summaryLabel: {
    fontSize: 13,
    fontFamily: "Inter-Medium",
    color: colors.gray,
  },
  activityDetail__summaryName: {
    fontSize: 20,
    fontFamily: "Inter-Bold",
    color: colors.black,
    textAlign: "center",
  },
  activityDetail__summaryDate: {
    fontSize: 14,
    fontFamily: "Inter-Normal",
    color: colors.gray,
    textAlign: "center",
  },
  activityDetail__summaryAmount: {
    marginTop: 4,
    fontSize: 22,
    fontFamily: "Inter-Bold",
    color: colors.black,
  },
  activityDetail__sectionCard: {
    ...baseCard,
    marginHorizontal: 16,
    gap: 12,
  },
  activityDetail__sectionTitle: {
    fontSize: 16,
    fontFamily: "Inter-SemiBold",
    color: colors.black,
  },
  activityDetail__chipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  activityDetail__chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.background,
    borderRadius: 20,
  },
  activityDetail__chipText: {
    fontSize: 13,
    fontFamily: "Inter-Medium",
    color: colors.black,
  },
  activityDetail__emptyText: {
    fontSize: 14,
    fontFamily: "Inter-Normal",
    color: colors.gray,
  },
  activityDetail__row: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  activityDetail__rowTextContainer: {
    flex: 1,
    gap: 2,
  },
  activityDetail__rowText: {
    fontSize: 14,
    fontFamily: "Inter-Normal",
    color: colors.black,
  },
  activityDetail__rowSubText: {
    fontSize: 13,
    fontFamily: "Inter-Normal",
    color: colors.gray,
  },
  activityDetail__descriptionText: {
    fontSize: 14,
    fontFamily: "Inter-Normal",
    color: colors.black,
    lineHeight: 20,
  },
  activityDetail__paymentRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  activityDetail__paymentLabel: {
    fontSize: 14,
    fontFamily: "Inter-Normal",
    color: colors.gray,
  },
  activityDetail__paymentValue: {
    fontSize: 16,
    fontFamily: "Inter-SemiBold",
    color: colors.black,
  },
  activityDetail__badge: {
    alignSelf: "flex-start",
    marginTop: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    fontSize: 12,
    fontFamily: "Inter-Medium",
    color: colors.black,
    backgroundColor: colors.background,
  },
  activityDetail__paymentMethodTag: {
    alignSelf: "flex-start",
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: "#FFE6C2",
    color: colors.black,
    fontSize: 13,
    fontFamily: "Inter-Medium",
  },
  activityDetail__paymentEmptyBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: colors.white,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.lightGray,
  },
  activityDetail__paymentEmptyText: {
    fontSize: 14,
    fontFamily: "Inter-Normal",
    color: colors.black,
  },
  activityDetail__ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  activityDetail__ratingText: {
    fontSize: 16,
    fontFamily: "Inter-SemiBold",
    color: colors.black,
  },
  activityDetail__ratingComment: {
    marginTop: 6,
    fontSize: 14,
    fontFamily: "Inter-Normal",
    color: colors.gray,
  },
  activityDetail__actionsCard: {
    ...baseCard,
    marginHorizontal: 16,
    gap: 10,
  },
  activityDetail__messageButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    paddingVertical: 14,
    gap: 8,
    backgroundColor: colors.primary,
  },
  activityDetail__messageButtonText: {
    fontSize: 16,
    fontFamily: "Inter-Bold",
    color: colors.white,
  },
  activityDetail__cancelButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    paddingVertical: 14,
    gap: 8,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.lightGray,
  },
  activityDetail__cancelButtonDisabled: {
    backgroundColor: colors.lightGray,
    borderColor: colors.lightGray,
  },
  activityDetail__cancelButtonText: {
    fontSize: 16,
    fontFamily: "Inter-Bold",
    color: "red",
  },
  activityDetail__cancelButtonTextDisabled: {
    color: colors.gray,
  },
  activityDetail__helpButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.lightGray,
    backgroundColor: colors.white,
  },
  activityDetail__helpText: {
    fontSize: 15,
    fontFamily: "Inter-SemiBold",
    color: colors.black,
  },
  activityDetail__modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  activityDetail__modalCard: {
    width: "100%",
    borderRadius: 18,
    backgroundColor: colors.white,
    padding: 24,
    gap: 16,
  },
  activityDetail__modalTitle: {
    fontSize: 18,
    fontFamily: "Inter-Bold",
    color: colors.black,
  },
  activityDetail__modalMessage: {
    fontSize: 14,
    fontFamily: "Inter-Normal",
    color: colors.gray,
  },
  activityDetail__modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
  },
  activityDetail__modalCancel: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  activityDetail__modalCancelText: {
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
    color: colors.black,
  },
  activityDetail__modalConfirm: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#E53935",
  },
  activityDetail__modalConfirmText: {
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
    color: colors.white,
  },
  activityDetail__emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 32,
  },
  activityDetail__emptyTitle: {
    fontSize: 18,
    fontFamily: "Inter-Bold",
    color: colors.black,
    textAlign: "center",
  },
  activityDetail__emptyMessage: {
    fontSize: 14,
    fontFamily: "Inter-Normal",
    color: colors.gray,
    textAlign: "center",
    lineHeight: 20,
  },
});
