export const servicesData = [
  { key: "1", name: "electricity" },
  { key: "2", name: "plumbing" },
  { key: "3", name: "gas" },
  { key: "4", name: "gardening" },
  { key: "5", name: "locksmith" },
  { key: "6", name: "painting" },
  { key: "7", name: "construction" },
  { key: "8", name: "pool" },
  { key: "9", name: "carpentry" },
  { key: "10", name: "glass" },
  { key: "11", name: "pets" },
  { key: "12", name: "security" },
  { key: "13", name: "ironwork" },
  { key: "14", name: "technology" },
  { key: "15", name: "beauty" },
  { key: "16", name: "vehicles" },
  { key: "17", name: "freight" },
  { key: "18", name: "events" },
  { key: "19", name: "photography" },
  { key: "20", name: "music" },
];
