import { StyleSheet } from "react-native";
import { colors } from "../../../../styles/globalStyles";

export const styles = StyleSheet.create({
  currentWork__body__container: {
    backgroundColor: colors.white,
    marginHorizontal: 16,
    marginTop: 30,
    borderRadius: 16,
    paddingHorizontal: 18,
    elevation: 2,
    paddingVertical: 20,
  },
  currentWork__body__title: {
    fontFamily: "Inter-Bold",
    fontSize: 17,
    color: colors.black,
    marginBottom: 6,
  },
  currentWork__body__clientRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.lightGray,
    paddingVertical: 12,
    marginTop: 6,
    marginBottom: 10,
  },
  currentWork__body__clientName: {
    fontFamily: "Inter-Bold",
    fontSize: 15,
    color: colors.black,
  },
  currentWork__body__clientLabel: {
    fontFamily: "Inter-Normal",
    fontSize: 13,
    color: colors.gray,
  },
  currentWork__body__callButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.green,
    alignItems: "center",
    justifyContent: "center",
  },
  currentWork__body__section: {
    marginTop: 10,
  },
  currentWork__body__sectionTitle: {
    fontFamily: "Inter-Bold",
    fontSize: 13,
    color: colors.gray,
    marginBottom: 6,
  },
  currentWork__body__sectionBox: {
    backgroundColor: colors.background,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  currentWork__body__sectionText: {
    fontFamily: "Inter-Normal",
    fontSize: 14,
    color: colors.black,
    marginLeft: 6,
  },
  currentWork__body__mapButton: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    paddingVertical: 10,
    backgroundColor: colors.black,
    gap: 8,
  },
  currentWork__body__mapButtonText: {
    color: colors.white,
    fontFamily: "Inter-SemiBold",
    fontSize: 14,
  },
  currentWork__body__servicesRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  currentWork__body__serviceTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.lightGray,
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  currentWork__body__serviceText: {
    fontFamily: "Inter-Normal",
    fontSize: 14,
    color: colors.black,
    marginLeft: 4,
  },
  currentWork__body__imagesContainer: {
    marginTop: 8,
  },
  currentWork__body__imageThumb: {
    width: 70,
    height: 70,
    borderRadius: 8,
    marginRight: 8,
  },
  currentWork__body__modalOverlay: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.8)",
    alignItems: "center",
    justifyContent: "center",
  },
  currentWork__body__modalImage: {
    width: "90%",
    height: "70%",
    resizeMode: "contain",
    borderRadius: 10,
  },
});
